version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && 
             service cron start && 
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    restart: always

  frontend:
    build: ./frontend
    container_name: react_app
    stdin_open: true
    tty: true
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: always

# admin@yahoo.com 123456789